name: Build

on: [push, pull_request]

jobs:
  build-host:
    env:
      MACOSX_DEPLOYMENT_TARGET: 10.14
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: windows-latest
            artifact-name: Windows x86
            architecture: x86
            build-options: ""
          - os: windows-latest
            artifact-name: Windows x86-64
            architecture: x64
            build-options: ""
          - os: macos-latest
            artifact-name: macOS x86-64
            architecture: x64
            build-options: ""

    name: "Build - ${{ matrix.artifact-name }}"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11
          architecture: ${{ matrix.architecture }}

      - name: Install Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer ${{ matrix.build-options }}
        if: ${{ github.repository_owner != 'wpilibsuite' || !startsWith(github.ref, 'refs/tags/v') }}

      - name: Build with Gradle (Release)
        run: ./gradlew build -PbuildServer -PreleaseMode ${{ matrix.build-options }}
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.artifact-name }}
          path: build/allOutputs

  build-docker:
    name: "Build - Linux x86-64"
    runs-on: ubuntu-latest
    container: wpilib/ubuntu-base:18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Install Toolchain
        run: ./gradlew installRoborioToolchain

      - name: Build with Gradle
        run: ./gradlew build -PbuildServer
        if: ${{ github.repository_owner != 'wpilibsuite' || !startsWith(github.ref, 'refs/tags/v') }}

      - name: Build with Gradle (Release)
        run: ./gradlew build -PbuildServer -PreleaseMode
        if: ${{ github.repository_owner == 'wpilibsuite' && startsWith(github.ref, 'refs/tags/v') }}

      - uses: actions/upload-artifact@v2
        with:
          name: Linux x86-64
          path: build/allOutputs